#!/bin/bash
# Automated Incident Response - Block Flagged Attackers
# Generated by Cybersecurity Log Scanner

iptables -A INPUT -s 10.0.0.50 -j DROP
echo '[REMEDIATION] Blocked malicious IP: 10.0.0.50'
iptables -A INPUT -s 172.16.4.12 -j DROP
echo '[REMEDIATION] Blocked malicious IP: 172.16.4.12'
iptables -A INPUT -s 185.220.101.5 -j DROP
echo '[REMEDIATION] Blocked malicious IP: 185.220.101.5'
iptables -A INPUT -s 198.51.100.77 -j DROP
echo '[REMEDIATION] Blocked malicious IP: 198.51.100.77'
iptables -A INPUT -s 203.0.113.88 -j DROP
echo '[REMEDIATION] Blocked malicious IP: 203.0.113.88'
iptables -A INPUT -s 45.33.32.156 -j DROP
echo '[REMEDIATION] Blocked malicious IP: 45.33.32.156'
