import re
import json
from collections import defaultdict

LOG_FILE = "server.log"
INCIDENT_REPORT_FILE = "incident_report.json"
FIREWALL_SCRIPT_FILE = "block_attackers.sh"

# Pre-compiled Regex Signatures for Attack Detection
RULES = [
    {
        "type": "SQL Injection",
        "pattern": re.compile(r"(UNION\s+SELECT|OR\s+'1'='1'|OR\s+1=1|--|;\s*DROP)", re.IGNORECASE),
        "severity": "HIGH"
    },
    {
        "type": "Cross-Site Scripting (XSS)",
        "pattern": re.compile(r"(<script.*?>|javascript:|onerror=|onload=)", re.IGNORECASE),
        "severity": "HIGH"
    },
    {
        "type": "Path Traversal / LFI",
        "pattern": re.compile(r"(\.\./|\.\.%2f|etc/passwd|win\.ini)", re.IGNORECASE),
        "severity": "CRITICAL"
    },
    {
        "type": "Malicious Web Scanner",
        "pattern": re.compile(r"(sqlmap|nikto|nmap|acunetix)", re.IGNORECASE),
        "severity": "MEDIUM"
    }
]

IP_PATTERN = re.compile(r"^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})")
STATUS_PATTERN = re.compile(r'"\s+(\d{3})\s+')
TIMESTAMP_PATTERN = re.compile(r'\[(.*?)\]')

def scan_logs(log_file):
    incidents = []
    unauthorized_attempts = defaultdict(int)
    flagged_ips = set()

    with open(log_file, "r") as f:
        for line_no, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            if not line:
                continue

            ip_match = IP_PATTERN.search(line)
            ip = ip_match.group(1) if ip_match else "UNKNOWN_IP"

            time_match = TIMESTAMP_PATTERN.search(line)
            timestamp = time_match.group(1) if time_match else "UNKNOWN_TIME"

            # Check for signature-based web attacks
            for rule in RULES:
                if rule["pattern"].search(line):
                    incidents.append({
                        "line": line_no,
                        "timestamp": timestamp,
                        "ip": ip,
                        "threat_type": rule["type"],
                        "severity": rule["severity"],
                        "raw_payload": line
                    })
                    flagged_ips.add(ip)

            # Check HTTP 401 Unauthorized for Brute-Force / Credential Stuffing
            status_match = STATUS_PATTERN.search(line)
            if status_match and status_match.group(1) == "401":
                unauthorized_attempts[ip] += 1

    # Evaluate brute force threshold (>= 3 failed authentications)
    for ip, count in unauthorized_attempts.items():
        if count >= 3:
            incidents.append({
                "line": "N/A (Multi-event)",
                "timestamp": "Aggregated",
                "ip": ip,
                "threat_type": "Brute Force Authentication",
                "severity": "HIGH",
                "details": f"{count} failed 401 Unauthorized attempts"
            })
            flagged_ips.add(ip)

    return incidents, flagged_ips, unauthorized_attempts

def export_siem_json(incidents, output_file):
    with open(output_file, "w") as f:
        json.dump(incidents, f, indent=2)

def generate_firewall_remediation(flagged_ips, output_file):
    with open(output_file, "w") as f:
        f.write("#!/bin/bash\n")
        f.write("# Automated Incident Response - Block Flagged Attackers\n")
        f.write("# Generated by Cybersecurity Log Scanner\n\n")
        for ip in sorted(flagged_ips):
            if ip != "UNKNOWN_IP":
                f.write(f"iptables -A INPUT -s {ip} -j DROP\n")
                f.write(f"echo '[REMEDIATION] Blocked malicious IP: {ip}'\n")

def display_dashboard(incidents, flagged_ips):
    print("=" * 65)
    print("     CYBERSECURITY LOG SCANNER & ANOMALY DETECTION REPORT")
    print("=" * 65)
    print(f"[*] Total Security Incidents Detected: {len(incidents)}")
    print(f"[*] Unique Malicious IPs Flagged:      {len(flagged_ips)}")
    print("-" * 65)

    print("\n[+] DETECTED THREAT DETAILS:")
    for inc in incidents:
        severity = inc['severity']
        print(f"  [{severity}] {inc['threat_type']} from {inc['ip']}")
        if "details" in inc:
            print(f"      Details: {inc['details']}")
        elif "raw_payload" in inc:
            print(f"      Payload: {inc['raw_payload'][:90]}...")

    print("\n" + "-" * 65)
    print("[+] AUTOMATED INCIDENT RESPONSE OUTPUTS:")
    print(f"  - SIEM JSON Log:       {INCIDENT_REPORT_FILE}")
    print(f"  - Firewall Rules:      {FIREWALL_SCRIPT_FILE} (Ready for iptables execution)")
    print("=" * 65)

def main():
    incidents, flagged_ips, _ = scan_logs(LOG_FILE)
    export_siem_json(incidents, INCIDENT_REPORT_FILE)
    generate_firewall_remediation(flagged_ips, FIREWALL_SCRIPT_FILE)
    display_dashboard(incidents, flagged_ips)

if __name__ == "__main__":
    main()
